#!/usr/bin/env python3

import requests
import datetime
from bs4 import BeautifulSoup
import os
import sys

def get_puzzles():
    year = datetime.datetime.now().year

    for day in range(1, 13):
        get_puzzle_from(day, year)

def get_puzzle_from(day, year):
    print("Getting day " + str(day) + " of year " + str(year))

    folder = "src/advent-of-code-2025/puzzles"
    if not os.path.exists(folder):
        os.makedirs(folder)

    with open("./.env", "r") as dotenv:
        cookie = dotenv.read()
    
    session = requests.Session()
    session.cookies.set("session", cookie, domain=".adventofcode.com")

    try:
        response = session.get("https://adventofcode.com/" + str(year) + "/day/" + str(day))
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        articles = soup.find_all("article", class_="day-desc")
        puzzle = [article.get_text() for article in articles]
        if (len(puzzle) == 1):
            content = puzzle[0].strip().replace(" ---", " ---\n")
        else:
            content = puzzle[0].strip().replace(" ---", " ---\n") + "\n\n" + puzzle[1].strip().replace(" ---", " ---\n")

    except requests.exceptions.RequestException as e:
        print(f"    Error fetching {year}: {day}")
        return None
    except Exception as e:
        print(f"    Unexpected error on {year}: {day}: {e}")
        return None

    if content is not None:
        with open(folder + "/day" + str(day) + ".txt", "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        get_puzzles()
    else:
        get_puzzle_from(sys.argv[1], sys.argv[2])