#!/usr/bin/env python3

import requests
import datetime
from bs4 import BeautifulSoup
import os
import sys

def get_puzzles():
    year = datetime.datetime.now().year

    for day in range(1, 26):
        get_puzzle_from(day, year)

def get_puzzle_from(day, year):
    print("Getting day " + str(day) + " of year " + str(year))

    folder = "src/advent-of-code-2025/puzzles"
    if not os.path.exists(folder):
        os.makedirs(folder)

    with open("./.env", "r") as dotenv:
        cookie = dotenv.read()
    
    session = requests.Session()
    session.cookies.set("session", cookie, domain=".adventofcode.com")

    request = session.get("https://adventofcode.com/" + str(year) + "/day/" + str(day))
    if request.status_code != 200:
        if request.status_code == 500:
            print("error: there was a server error. maybe your session cookie is wrong? (500)")
        elif request.status_code == 404:
            print("error: looks like there is no problem on the given date. (404)")
        else:
            print("error: http code " + str(request.status_code))
        return None

    soup = BeautifulSoup(request.text, "html.parser")

    articles = soup.find_all("article", class_="day-desc")
    puzzle = [article.get_text() for article in articles]
    content = puzzle[0].strip().replace(" ---", " ---\n") + "\n\n" + puzzle[1].strip().replace(" ---", " ---\n")

    if content is not None:
        with open(folder + "/day" + str(day) + ".txt", "w") as f:
            f.write(content)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        get_puzzles()
    else:
        get_puzzle_from(sys.argv[1], sys.argv[2])