#!/usr/bin/env python3

import argparse
from pathlib import Path
from os import path;
from datetime import date
from aocd import get_data
import subprocess
import webbrowser

PARSER = argparse.ArgumentParser(
    prog="./start", description="Scaffold a new Advent of Code solution"
)
PARSER.add_argument(
    "day",
    type=int,
    help=(
        "Which puzzle day to start, between [1,25]."
        " Defaults to the next day without a folder (matching `day_N`) in that year."
    ),
    nargs="?",
)

if __name__ == "__main__":
    ARGS = PARSER.parse_args()

    day = ARGS.day if ARGS.day is not None else date.today().day

    if not 1 <= day <= 25:
        PARSER.error(f"day {day} is not in range [1,25]")

    print("doing day", day)

    day_path = Path("src/advent-of-code-2025/solutions", f"day{day:02}")

    day_path.mkdir(parents=True, exist_ok=True)

    # bgn get input ##############

    ## puzzle

    with open('.env') as f: aoc_session = f.read()
    contents_puzzle = get_data(day=day, year=2025, session=aoc_session)

    day_fullpath = Path(day_path, "input.txt")

    if path.exists(day_fullpath): 
        open(day_fullpath, 'w').close()

    with open(day_fullpath, "a") as f:
        for line in contents_puzzle:
            f.write(line)

    ## test

    command = "aocd " + str(day) + " 2025 --example"
    result = subprocess.run(command, shell=True, text=True, capture_output=True)
    contents_test = result.stdout

    test_fullpath = Path(day_path, "input.test.txt")

    if path.exists(test_fullpath):
        open(test_fullpath, 'w').close()

    with open(test_fullpath, "a") as f:
        for line in contents_test:
            f.write(line)

    print("Downloaded input files")

    # end get input ##############

    ## puzzle

    command = "./get-puzzles " + str(day) + " 2025"
    result = subprocess.run(command, shell=True, text=True)

    # end get puzzle ##############

    solution_path = Path(day_path, "solution.py")
    tests_path = Path(day_path, "tests.py")

    if solution_path.exists():
        print("skipping solution creation, file already exists")
    else:
        template = Path("src/advent-of-code-2025/misc/example_solution.py.tmpl").read_text()
        replaced_template = template.replace("<YEAR>", "2025").replace("<DAY>", str(day))
        solution_path.write_text(replaced_template)
        print("Created a new Solution file at", solution_path)

        template = Path("src/advent-of-code-2025/misc/tests.py.tmpl").read_text()
        replaced_template = template.replace("<DAY>", str(day).zfill(2))
        tests_path.write_text(replaced_template)
        print("Created a new Test file at", tests_path)

        print("Open AOC day in the browser")
        url = "https://adventofcode.com/2025/day/" + str(day)
        webbrowser.open(url)
